name: Build APK Manual

on:
  push:
  workflow_dispatch: # Isso cria o botÃ£o de "Play" manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Baixar Seus Arquivos
        uses: actions/checkout@v3

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: â˜• Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ“± Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: ğŸ“¦ Instalar Flet 0.22.0 e Compilar
        run: |
          pip install flet==0.22.0
          yes | flet build apk --verbose

      - name: ğŸ“¤ Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-TOMATE-FINAL
          path: "**/*.apk"
